### ISSUE TITLE
ECU-R not restarting

### ISSUE THREAD

**Issue by crispy78** [ksheumaker/homeassistant-apsystems_ecur#128]
Hi there,

I see the ECU-R has an automated restart function when it's not providing data, how does that work?
Currently I have the latest available software installed on Home Assistant, but every day or two I have to preform some miracles to get it to work again. All entries become unavailable, so I reload and reconfigure the addon, after that fails I restart HA and reboot de ECU-R and after that fails I redownload the plugin. A lot of hastle for one device IMO. binary_sensor.ecu_restart shows "off", did I forget to enable something?

PS. Today I've written APSystems because the device is new but the software isn't; JQuery 1.8.2 (current version 3.6.1), Bootstrap 3.2.0 (current version 5.2.2), My97 Datepicker 4.8beta (current version 4.8.5) and Highcharts 4.0.3 (current version 10.2.1) for example. Main reason is that I get a 404-error when I login into the device by it's IP-address (I should be loggin in from {ipaddress}/index.php/management/), also when clicking on the logo you'll be transfered to a non-functioning site. Hope they'll update their software so we can safely and comfortly use it in 2023 :-)

**Comment by HAEdwin** [comment]
Your issue is now solved in v1.2.23 where in the previous version an infinite loop caused the integration to get non-responsive. See readme on how the reset works and also read #115 for more background info on this.

If your ECU is just installed, it might take a while but it will be updated with the latest firmware automatically. In most cases this takes place during maintenance in the early morning.
