### ISSUE TITLE
Feature request: module in safe mode

### ISSUE THREAD

**Issue by MrLivelong** [ksheumaker/homeassistant-apsystems_ecur#176]
Hello,

Because of high voltages in my neighborhood, I would like to measure when a module is in safe mode.
Is it possible to add this?

thanks in advance!

**Comment by HAEdwin** [comment]
You may want to look at ways to monitor grid frequency. Changes in grid frequency are used to remotely shut down inverters to protect the grid. I will close this issue because it's hard to supply a generic solution as well as ways to reproduce this for all models inverters and ECU's for testing purposes. I simply don't have the resources to reproduce this. Might any other question arrise, feel free to open a new issue.
