### ISSUE TITLE
ECU-C sometimes Today energy drops to 0 for a couple of minutes

### ISSUE THREAD

**Issue by gratjetost** [ksheumaker/homeassistant-apsystems_ecur#193]
running the latest v1.2.29 with a ECU-C.
Noticed already a couple of times the Today energy suddenly drops to 0. And after that comes back to its normal value.
Leading in the HACS energy tab for a big spike and incorrect value.

![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/7c70f0d8-97d9-409e-a8c1-3d13163ddc77)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/362d401b-378b-486f-8c36-214b87c78f1a)

![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/152de044-41df-4de8-bb5b-a0d89789eaca)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/1ce3570a-a290-4b59-9e32-73dd57a6ee4d)

**Comment by HAEdwin** [comment]
When did this issue first appear? This data comes from the ECU-C and identified as ECU data. What you can do to avoid this is adding the following check to APSystemsSocket.py:
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/82239374/7c52d5ad-c579-4b99-b1c5-18f1f367971c)

**Comment by GillesBOULANGER** [comment]
Same problem for me with ECU-C (V1.2.29), everything works perfectly and suddenly the output drops to 0. Then it comes back after a few minutes but the values indicated are very different from those provided by the android application.  On the apsystem website, the values seem to be good too. any ideas ?

**Comment by HAEdwin** [comment]
I'll hope to pre-release a version this weekend which should solve this issue.

**Comment by HAEdwin** [comment]
The pre-release v1.2.31b contains an extra ECU query that introduces (part of) the use of energy history data. This is a query I previously described but was never needed (we thought). To compensate load time for the integration, I shortened the sleep-time between opening and closing the port. I also introduced the keepalive, a careful introduction to removing this sleep-time and keeping the port open. Success will depend greatly on compatibility with different ECU models and firmware. If you own an older model starting with 2160xxxxxxx ECU-R, you can even leave out the open/close functions, but does this work for other ECU models? I could make it optional in the UI settings. Anyway it should solve this issue. Please let me know if it does so that I can close the issue.

**Comment by HAEdwin** [comment]
I'm pretty sure Today Energy's issue has been resolved for the ECU-R, ECU-B and ECU-C. I'm closing this issue, if anything pops up, feel free to create a new issue.
