### ISSUE TITLE
Changing Query time seems to do nothing

### ISSUE THREAD

**Issue by Xplode85** [ksheumaker/homeassistant-apsystems_ecur#43]
I've tried query time 60s and 120s, but it doesn't seem to actually change the query time.
I know the lower query time can cause instability, but i'd like to test and find the actual limit where problems will appear.
Would also love if a method to change query time without reinstallering the integration could be added.

To help with instability because of shorter query times would it help to not query some entities? Temperature, voltage, frequency signal etc isn't something that everyone will need or they could be queried at longer intervals.

**Comment by ksheumaker** [comment]
What ECU do they have, and which inverters? and what is the firmware the integration is reporting?  

Are there stability issues, or is has it been working?  

I have 25 panels (on 7 QS1 inverters) and it has been really stable for me.  We aren't sure the amount of data or number of inverters is more problematic or not, but 40 is the most I've heard, so I'm interested in feedback from a system like that.

**Comment by Xplode85** [comment]
I have set querries to 120s now and i see updates at 240s and 360s interval
![image](https://user-images.githubusercontent.com/72715336/154727500-d8975599-e8d2-4021-abda-7c251613ce6f.png)

**Comment by ksheumaker** [comment]
If the data doesn't change between those intervals,  HA doesn't log it.  If you really want to make sure it's querying every 120s then put the logging for the integration in debug mode, and you'll see messages about it opening the connection to the ECU.

**Comment by ksheumaker** [comment]
> He's using 285w panels and one of the panels mounted vertical on the wall has been up to 281w, snow on the ground might have helped this thou...will continue to monitor the max power produced on this panel.

My panels are bigger than 300W since the placement of them isn't ideal because of the shape of my roof.  Here's what I'm seeing right now:

![Screen Shot 2022-02-18 at 11 23 10 AM](https://user-images.githubusercontent.com/12651/154731831-4579528c-cc46-4976-b286-25fc8876572a.png)

We had 8 inches of snow yesterday, and with the drifts some of them are still pretty covered.  I'm not sure how I get greater than 300W production though, since my understanding is the QS1 can only do 300W per channel.  I don't know if the data is incorrect, or if they under-report the specifications on them.   The data I get here is the same when I login to APSystems EMA web app though.

**Comment by HAEdwin** [comment]
I think @Xplode85, the graph is somewhat confusing with this interval/timing because it just missed the update from the ECU so it will show in the next. The pattern long (6 minutes) -short (4 minutes) -long (6 minutes) -short (4 minutes) confirms this. On average the information of the ECU is still updated once every five minutes. This is a slight disadvantage of intervals larger than one minute but it should not really be an issue, no data is missed with intervals < 5 minutes unless there is a communication error, the probability increases with large intervals.

**Comment by HAEdwin** [comment]
@Xplode85 Did my explanation help to solve this problem? If so would you please close this issue? Many thanks.
